# Generated by Django 5.1 on 2024-10-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='default/default.png', null=True, upload_to='users/profile_pic'),
        ),
    ]
