# Generated by Django 5.1 on 2025-01-27 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='color',
        ),
    ]
