# Generated by Django 5.1 on 2025-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_cart_color_remove_cartorderitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
