# Generated by Django 5.1 on 2025-06-25 14:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
